export const dishNames: string[] = [
  "Fluffy Pancakes",
  "Belgian Waffles",
  "French Toast",
  "Breakfast Burrito",
  "Eggs Benedict",
  "Shakshuka",
  "Avocado Toast",
  "Breakfast Sandwich",
  "Omelette",
  "Frittata",
  "Breakfast Hash",
  "Quiche",
  "Crepes",
  "Breakfast Bowl",
  "Granola Parfait",
  "Smoothie Bowl",
  "Breakfast Tacos",
  "Huevos Rancheros",
  "Bagel and Lox",
  "Breakfast Pizza",
  "Cinnamon Rolls",
  "Scones",
  "Muffins",
  "Coffee Cake",
  "Breakfast Quesadilla",
  "Egg Muffins",
  "Chia Pudding",
  "Overnight Oats",
  "Breakfast Casserole",
  "Dutch Baby Pancake",
  "Biscuits and Gravy",
  "English Breakfast",
  "Protein Pancakes",
  "Sweet Potato Hash",
  "Breakfast Skillet",
  "Croque Madame",
  "Smoked Salmon Bagel",
  "Breakfast Risotto",
  "Morning Glory Muffins",
  "Breakfast Flatbread",
  "Club Sandwich",
  "Caesar Salad",
  "Chicken Wrap",
  "Tomato Soup",
  "Grilled Cheese",
  "Cobb Salad",
  "BLT Sandwich",
  "Tuna Salad",
  "Caprese Sandwich",
  "Greek Salad",
  "Quinoa Bowl",
  "Pasta Salad",
  "Chicken Noodle Soup",
  "Turkey Sandwich",
  "Veggie Wrap",
  "Asian Noodle Bowl",
  "Minestrone Soup",
  "Buddha Bowl",
  "Panini",
  "Soup and Salad Combo",
  "Rice Bowl",
  "Pita Pocket",
  "Nicoise Salad",
  "Pulled Pork Sandwich",
  "French Onion Soup",
  "Falafel Wrap",
  "Chicken Caesar Wrap",
  "Mediterranean Bowl",
  "Pho Bowl",
  "Ramen Bowl",
  "Burrito Bowl",
  "Lobster Roll",
  "Po Boy Sandwich",
  "Cuban Sandwich",
  "Banh Mi",
  "Spaghetti Carbonara",
  "Grilled Salmon",
  "Beef Stroganoff",
  "Chicken Parmesan",
  "Lasagna",
  "Pork Chops",
  "Beef Tacos",
  "Chicken Stir Fry",
  "Meatloaf",
  "Roast Chicken",
  "Fish and Chips",
  "Shepherd's Pie",
  "Beef Bourguignon",
  "Chicken Curry",
  "Paella",
  "Risotto",
  "Pot Roast",
  "BBQ Ribs",
  "Stuffed Peppers",
  "Chicken Alfredo",
  "Beef Enchiladas",
  "Shrimp Scampi",
  "Teriyaki Chicken",
  "Pulled Pork",
  "Lamb Chops",
  "Duck Confit",
  "Sea Bass",
  "Beef Wellington",
  "Osso Buco",
  "Coq au Vin",
  "Jambalaya",
  "Chicken Tikka Masala",
  "Pad Thai",
  "Beef Bulgogi",
  "Moussaka",
  "Chicken Marsala",
  "Pork Tenderloin",
  "Cioppino",
  "Chicken Cacciatore",
  "Beef Brisket",
  "Salmon Teriyaki",
  "Pork Carnitas",
  "Chicken Piccata",
  "Meatballs",
  "Roasted Turkey",
  "Beef Fajitas",
  "Shrimp Fried Rice",
  "Chicken Shawarma",
  "Lamb Curry",
  "Pork Schnitzel",
  "Chicken Souvlaki",
  "Beef Kebabs",
  "Fish Tacos",
  "Pork Ramen",
  "Chicken Adobo",
  "Beef Rendang",
  "Duck Breast",
  "Lobster Thermidor",
  "Chicken Biryani",
  "Pork Belly",
  "Bruschetta",
  "Buffalo Wings",
  "Spring Rolls",
  "Hummus",
  "Guacamole",
  "Spinach Artichoke Dip",
  "Deviled Eggs",
  "Mozzarella Sticks",
  "Nachos",
  "Jalapeño Poppers",
  "Crab Cakes",
  "Caprese Skewers",
  "Cheese Board",
  "Stuffed Mushrooms",
  "Prosciutto Melon",
  "Shrimp Cocktail",
  "Chicken Satay",
  "Potato Skins",
  "Meatballs",
  "Quesadilla",
  "Edamame",
  "Onion Rings",
  "Calamari",
  "Pigs in Blanket",
  "Chicken Tenders",
  "Samosas",
  "Empanadas",
  "Crostini",
  "Cheese Fondue",
  "Fried Pickles",
  "Chocolate Cake",
  "Cheesecake",
  "Brownies",
  "Tiramisu",
  "Apple Pie",
  "Crème Brûlée",
  "Ice Cream Sundae",
  "Cookies",
  "Cupcakes",
  "Panna Cotta",
  "Chocolate Mousse",
  "Lemon Bars",
  "Red Velvet Cake",
  "Carrot Cake",
  "Banana Bread",
  "Fudge",
  "Macarons",
  "Eclairs",
  "Cannoli",
  "Churros",
  "Tres Leches Cake",
  "Flan",
  "Key Lime Pie",
  "Pecan Pie",
  "Blueberry Pie",
  "Chocolate Chip Cookies",
  "Snickerdoodles",
  "Peanut Butter Cookies",
  "Oatmeal Cookies",
  "Sugar Cookies",
  "Chocolate Truffles",
  "Rice Pudding",
  "Bread Pudding",
  "Fruit Tart",
  "Lemon Tart",
  "Chocolate Soufflé",
  "Pavlova",
  "Baked Alaska",
  "Banoffee Pie",
  "Mississippi Mud Pie",
  "Black Forest Cake",
  "Opera Cake",
  "Molten Lava Cake",
  "Angel Food Cake",
  "Pound Cake",
  "Strawberry Shortcake",
  "Pumpkin Pie",
  "Chocolate Fondue",
  "Gelato",
  "Sorbet",
  "Sourdough Bread",
  "Baguette",
  "Focaccia",
  "Croissants",
  "Brioche",
  "Ciabatta",
  "Challah",
  "Pita Bread",
  "Naan",
  "Dinner Rolls",
  "Bagels",
  "English Muffins",
  "Pretzel",
  "Cornbread",
  "Irish Soda Bread",
  "Rye Bread",
  "Whole Wheat Bread",
  "Garlic Bread",
  "Pizza Dough",
  "Flatbread",
  "Pumpernickel",
  "Multi-Grain Bread",
  "Sandwich Bread",
  "Monkey Bread",
  "Pull-Apart Bread",
  "Vegetable Stir Fry",
  "Lentil Soup",
  "Veggie Burger",
  "Tofu Scramble",
  "Chickpea Curry",
  "Vegetable Lasagna",
  "Falafel",
  "Veggie Tacos",
  "Mushroom Risotto",
  "Ratatouille",
  "Eggplant Parmesan",
  "Vegetable Pad Thai",
  "Black Bean Burrito",
  "Cauliflower Steak",
  "Portobello Burger",
  "Stuffed Zucchini",
  "Veggie Sushi Roll",
  "Vegetable Biryani",
  "Tempeh Bowl",
  "Jackfruit Tacos",
  "Vegan Pizza",
  "Lentil Bolognese",
  "Quinoa Stuffed Peppers",
  "Vegetable Korma",
  "Tofu Stir Fry",
  "Vegan Mac and Cheese",
  "Cauliflower Wings",
  "Vegetable Spring Rolls",
  "Bean Chili",
  "Veggie Kebabs",
  "Garlic Shrimp Pasta",
  "Chicken Quesadilla",
  "15-Minute Fried Rice",
  "Quick Chicken Teriyaki",
  "Easy Beef Tacos",
  "Simple Pasta Aglio e Olio",
  "Pan-Seared Salmon",
  "Quick Chicken Fajitas",
  "Easy Stir Fry",
  "Instant Noodles Upgrade",
  "Quick Omelet",
  "Fast Fried Egg Sandwich",
  "Microwave Mug Cake",
  "10-Minute Pizza",
  "Quick Quesadilla",
  "Speed Chicken Parmesan",
  "Rapid Rice Bowl",
  "Express Pasta Primavera",
  "Swift Shrimp Tacos",
  "Fast Fish Tacos",
  "Quick Grilled Cheese Deluxe",
  "Speedy Spaghetti",
  "Rapid Ramen",
  "Express Egg Fried Rice",
  "Quick Chicken Wrap",
  "Fast Thai Basil Chicken",
  "Quick Pesto Pasta",
  "Easy Chicken Salad",
  "Quick Tuna Melt",
  "Fast Breakfast Burrito",
  "Quick Caprese Sandwich",
  "Easy Greek Salad",
  "Quick Smoothie Bowl",
  "Fast Avocado Toast",
  "Quick Chicken Sandwich",
  "Easy Veggie Wrap",
  "Quick Protein Bowl",
  "Fast Noodle Soup",
  "Quick Cheese Pizza",
  "Easy Flatbread Pizza",
  "Grilled Chicken Salad",
  "Quinoa Power Bowl",
  "Baked Salmon with Vegetables",
  "Turkey Lettuce Wraps",
  "Greek Yogurt Parfait",
  "Kale Caesar Salad",
  "Zucchini Noodles",
  "Cauliflower Rice Bowl",
  "Protein Smoothie",
  "Green Smoothie Bowl",
  "Grilled Chicken Breast",
  "Steamed Fish with Broccoli",
  "Egg White Omelet",
  "Turkey Burger",
  "Tuna Poke Bowl",
  "Low-Carb Chicken Wings",
  "Spiralized Vegetable Pasta",
  "Lettuce Wrap Tacos",
  "Protein Pancakes",
  "Chia Seed Pudding",
  "Grilled Vegetable Platter",
  "Baked Cod",
  "Turkey Meatballs",
  "Shrimp Lettuce Cups",
  "Chicken Zoodle Soup",
  "Almond-Crusted Chicken",
  "Baked Chicken Tenders",
  "Vegetable Soup",
  "Lean Beef Stir Fry",
  "Low-Fat Greek Bowl",
  "Authentic Pad Thai",
  "Classic Paella",
  "Traditional Biryani",
  "French Cassoulet",
  "Italian Osso Buco",
  "Japanese Ramen",
  "Korean Bibimbap",
  "Vietnamese Pho",
  "Thai Green Curry",
  "Indian Butter Chicken",
  "Greek Moussaka",
  "Spanish Tapas",
  "Mexican Mole",
  "Lebanese Shawarma",
  "Moroccan Tagine",
  "Chinese Kung Pao Chicken",
  "Japanese Tempura",
  "Turkish Kebab",
  "Brazilian Feijoada",
  "Peruvian Ceviche",
  "Argentine Empanadas",
  "German Schnitzel",
  "Russian Beef Stroganoff",
  "Polish Pierogi",
  "Hungarian Goulash",
  "Ethiopian Wat",
  "Malaysian Rendang",
  "Indonesian Satay",
  "Filipino Adobo",
  "Caribbean Jerk Chicken",
  "Jamaican Curry Goat",
  "Cuban Ropa Vieja",
  "Portuguese Bacalhau",
  "Swedish Meatballs",
  "Danish Smørrebrød",
  "Austrian Sachertorte",
  "Belgian Carbonnade",
  "Dutch Stamppot",
  "Swiss Fondue",
  "Norwegian Gravlax",
];
